'use client'

/**
 * Enterprise DS v3 — Dropzone & Upload
 * Figma nodes: Single: 4196-61262  ·  Multiple: 5061-91899
 *
 * Anatomy
 *   DropzoneAndUpload  — root wrapper: optional label · drop target · file list · helper/error text
 *   DropZone           — dashed-border drag-and-drop area; also triggers a hidden <input type="file">
 *   FileRow            — one uploaded file: type icon · name + size · progress bar · remove button
 *
 * Variants
 *   single   — accepts one file at a time; a "Replace file" affordance replaces the dropzone after upload
 *   multiple — accepts N files; a scrollable file list grows below the persistent drop area
 *
 * States (DropZone area)
 *   default    — neutral dashed border, transparent background
 *   hover      — positive-green border + subtle bg tint (mouse over or keyboard focus)
 *   drag-over  — same green tint, deeper on active drop
 *   error      — negative/red border + error text below
 *   disabled   — 48% opacity, not-allowed cursor, no interaction
 *
 * Themes  — light · dark
 */

import React, { useState, useRef, useCallback, useId, useEffect } from 'react'
import { CheckOutline, CloseOutline, DeleteOutline } from '@/components/ui/icons'
import { cn } from './utils'
import { typography, semantic, translucent, borderWidth, spacing, radius, elevation, scale, opacity } from '@/lib/tokens'
import { Button } from './button'

const s = semantic
const t = translucent

// ─── Types ────────────────────────────────────────────────────────────────────

export type DropzoneVariant = 'single' | 'multiple'
export type DropzoneTheme   = 'light' | 'dark'

export interface UploadFile {
  /** Stable key — auto-generated by makeUploadFile; supply your own in controlled usage */
  id:        string
  /** Original File object — undefined when constructing placeholder / preview data */
  file?:     File
  /** Display name */
  name:      string
  /** Formatted file size, e.g. "1.2 MB" */
  size:      string
  /** Upload progress 0–100. Omit or undefined = no progress bar */
  progress?: number
  /** Per-file error message */
  error?:    string
  /** Current upload lifecycle state */
  status?:   'uploading' | 'success' | 'error'
}

export interface DropzoneAndUploadProps {
  /** 'single' | 'multiple'. Default: 'single' */
  variant?:     DropzoneVariant
  /** 'light' | 'dark'. Default: 'light' */
  theme?:       DropzoneTheme
  /** Controlled file list */
  files?:       UploadFile[]
  /** Uncontrolled initial files */
  defaultFiles?: UploadFile[]
  /** Called whenever files are added or removed */
  onChange?:    (files: UploadFile[]) => void
  /** Called when a single file is removed; receives the removed file id */
  onRemove?:    (id: string) => void
  /** HTML accept string, e.g. "image/*,.pdf" */
  accept?:      string
  /** Max size per file in bytes */
  maxSize?:     number
  /** Human-readable list of accepted formats shown inside the drop area, e.g. "JPG, PNG, PDF" */
  acceptLabel?: string
  /** Optional label rendered above the dropzone */
  label?:       string
  /** Helper text shown below the dropzone */
  helperText?:  string
  /** Error message — triggers red border + error text */
  error?:       string
  /** Disables the entire component */
  disabled?:    boolean
  /** Appends a required asterisk to the label */
  required?:    boolean
  /** Controls which visual state the drop area renders. Default: 'idle' */
  uploadState?: DropzoneUploadState
  /** Filename displayed inside the drop area during the 'uploading' state */
  uploadingFileName?: string
  /** Called when the cancel × button is clicked during the 'uploading' state */
  onCancelUpload?: () => void
  className?:   string
  style?:       React.CSSProperties
}

// ─── Design Tokens ────────────────────────────────────────────────────────────
// All values sourced from Enterprise DS v3 token set.

const tokens = {
  light: {
    // Drop area
    dropBg:           t.transparent,
    dropBgHover:      s.background.positive.defaultSubtle.light,
    dropBgError:      s.background.negative.defaultSubtle.light,
    dropBorder:       s.border.strong.light,
    dropBorderHover:  s.border.positive.light,
    dropBorderError:  s.border.negative.light,
    dropIconDefault:  s.foreground.neutral.defaultDeep.light,
    dropIconHover:    s.foreground.positive.default.light,
    // Labels
    labelColor:       s.foreground.neutral.defaultDeep.light,
    titleColor:       s.foreground.default.primary.light,
    subtitleColor:    s.foreground.default.secondary.light,
    browseColor:      s.foreground.positive.default.light,
    // File row
    rowBg:            s.background.page.light,
    rowBgHover:       s.background.containerSecondary.light,
    rowBorder:        s.border.default.light,
    fileNameColor:    s.foreground.default.primary.light,
    fileSizeColor:    s.foreground.default.secondary.light,
    fileIconColor:    s.foreground.neutral.defaultDeep.light,
    removeColor:      s.foreground.default.secondary.light,
    removeHoverColor: s.foreground.negative.default.light,
    // Progress
    progressTrack:    s.border.default.light,
    progressFill:     s.border.positive.light,
    // States
    errorText:        s.foreground.negative.default.light,
    helperTextColor:  s.foreground.default.secondary.light,
    successIcon:      s.foreground.positive.default.light,
    focusRing:        s.border.focus.light,
    disabledText:     s.foreground.default.disabled.light,
  },
  dark: {
    dropBg:           t.transparent,
    dropBgHover:      translucent.green10,   // nearest to Figma rgba(150,220,20,0.08) — green10 is 0.10 opacity, accepted
    dropBgError:      s.background.negative.defaultSubtle.dark,
    dropBorder:       s.border.default.dark,
    dropBorderHover:  s.border.positive.dark,
    dropBorderError:  s.border.negative.dark,
    dropIconDefault:  s.foreground.default.disabled.light,   // grey[500] — intentional: muted icon on dark canvas
    dropIconHover:    s.foreground.positive.default.dark,
    labelColor:       s.foreground.default.disabled.light,   // grey[500]
    titleColor:       s.foreground.default.primary.dark,
    subtitleColor:    s.foreground.default.disabled.light,   // grey[500] — closest to #BBBBBB on dark
    browseColor:      s.foreground.positive.default.dark,
    rowBg:            s.background.container.dark,
    rowBgHover:       s.background.container.dark,
    rowBorder:        s.border.default.dark,
    fileNameColor:    s.foreground.default.primary.dark,
    fileSizeColor:    s.foreground.default.disabled.light,   // grey[500]
    fileIconColor:    s.foreground.default.disabled.light,   // grey[500]
    removeColor:      s.foreground.default.disabled.light,   // grey[500]
    removeHoverColor: s.foreground.negative.default.dark,
    progressTrack:    s.border.default.dark,
    progressFill:     s.border.positive.dark,
    errorText:        s.foreground.negative.default.dark,
    helperTextColor:  s.foreground.default.disabled.light,   // grey[500]
    successIcon:      s.foreground.positive.default.dark,
    focusRing:        s.border.focus.dark,
    disabledText:     s.foreground.default.disabled.dark,
  },
}

type TokenSet = typeof tokens[DropzoneTheme]

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B'
  const k     = 1024
  const sizes = ['B', 'KB', 'MB', 'GB']
  const i     = Math.floor(Math.log(bytes) / Math.log(k))
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`
}

function makeUploadFile(file: File): UploadFile {
  return {
    id:   `${file.name}-${Date.now()}-${Math.random().toString(36).slice(2)}`,
    file,
    name: file.name,
    size: formatBytes(file.size),
  }
}

// ─── Upload Cloud SVG ─────────────────────────────────────────────────────────

function UploadCloudIcon({ color, size = 40 }: { color: string; size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 40 40" fill="none" aria-hidden>
      <path
        d="M27 27C30.3137 27 33 24.3137 33 21C33 18.1716 31.1274 15.7854 28.5139 15.1239C28.5698 14.7563 28.5984 14.3806 28.5984 14C28.5984 10.134 25.4644 7 21.5984 7C19.5453 7 17.6937 7.87579 16.3797 9.27359C15.6726 8.86329 14.8479 8.625 13.9688 8.625C11.1322 8.625 8.83331 10.9239 8.83331 13.7605C8.83331 13.9301 8.84199 14.098 8.85921 14.2636C6.60999 15.0897 5 17.2638 5 19.8125C5 23.1262 7.68629 25.8125 11 25.8125"
        stroke={color}
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M25.3333 24.6667L20 19.3333L14.6667 24.6667"
        stroke={color}
        strokeWidth="1.75"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M20 19.3333V33"
        stroke={color}
        strokeWidth="1.75"
        strokeLinecap="round"
      />
    </svg>
  )
}

// ─── File Type SVG ────────────────────────────────────────────────────────────

function FileTypeIcon({ name, defaultColor }: { name: string; defaultColor: string }) {
  const ext = name.split('.').pop()?.toLowerCase() ?? ''

  const accentColor =
    ['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'avif'].includes(ext) ? s.foreground.complimentary.mint.default.light :
    ['pdf'].includes(ext)                                                ? s.foreground.negative.default.light :
    ['doc', 'docx'].includes(ext)                                        ? s.foreground.information.default.light :
    ['xls', 'xlsx', 'csv'].includes(ext)                                 ? s.foreground.positive.default.light :
    ['zip', 'rar', '7z', 'tar', 'gz'].includes(ext)                      ? s.foreground.warning.default.light :
    ['mp4', 'mov', 'avi', 'mkv'].includes(ext)                           ? s.foreground.complimentary.pink.default.light :
    ['mp3', 'wav', 'aac', 'flac'].includes(ext)                          ? s.foreground.ai.default.light :
    defaultColor

  return (
    <svg width="20" height="24" viewBox="0 0 20 24" fill="none" aria-hidden>
      <path
        d="M2 2C2 1.44772 2.44772 1 3 1H13L19 7V22C19 22.5523 18.5523 23 18 23H3C2.44772 23 2 22.5523 2 22V2Z"
        fill={accentColor}
        fillOpacity="0.10"
        stroke={accentColor}
        strokeWidth="1.25"
      />
      <path
        d="M13 1L19 7H13V1Z"
        fill={accentColor}
        fillOpacity="0.25"
        stroke={accentColor}
        strokeWidth="1.25"
        strokeLinejoin="round"
      />
      {ext && (
        <text
          x="10.5"
          y="17"
          textAnchor="middle"
          fontSize="5"
          fontWeight="700"
          fill={accentColor}
          fontFamily="Source Sans Pro, sans-serif"
          letterSpacing="0.5"
        >
          {ext.toUpperCase().slice(0, 3)}
        </text>
      )}
    </svg>
  )
}

// ─── Spinner Icon (uploading state) ──────────────────────────────────────────

function SpinnerIcon({ trackColor, fillColor, size = 48 }: { trackColor: string; fillColor: string; size?: number }) {
  return (
    <div
      className="animate-spin"
      aria-hidden
      style={{
        width:           size,
        height:          size,
        borderRadius:    radius.circle,
        border:          `${borderWidth.thick} solid ${trackColor}`,
        borderTopColor:  fillColor,
        flexShrink:      0,
      }}
    />
  )
}

// ─── Upload Complete Icon (completed state) ───────────────────────────────────

function UploadCompleteIcon({ color, size = 52 }: { color: string; size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 52 52" fill="none" aria-hidden>
      <circle cx="26" cy="26" r="23" stroke={color} strokeWidth="2" />
      <path d="M15 26L22 33L37 18" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// ─── Document Round Icon (multi-upload uploading row) ─────────────────────────

function DocRoundIcon({ bgColor, iconColor }: { bgColor: string; iconColor: string }) {
  return (
    <span style={{ width: scale[800], height: scale[800], borderRadius: radius.circle, backgroundColor: bgColor, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
      <svg width="16" height="20" viewBox="0 0 16 20" fill="none" aria-hidden>
        <path d="M2 2C2 1.45 2.45 1 3 1H10L15 6V18C15 18.55 14.55 19 14 19H3C2.45 19 2 18.55 2 18V2Z"
          fill={iconColor} fillOpacity="0.15" stroke={iconColor} strokeWidth="1.2" />
        <path d="M10 1L15 6H10V1Z" fill={iconColor} fillOpacity="0.3" stroke={iconColor} strokeWidth="1.2" strokeLinejoin="round" />
        <line x1="4.5" y1="10" x2="11.5" y2="10" stroke={iconColor} strokeWidth="1" strokeLinecap="round" />
        <line x1="4.5" y1="13" x2="11.5" y2="13" stroke={iconColor} strokeWidth="1" strokeLinecap="round" />
      </svg>
    </span>
  )
}

// ─── Filled checkmark icon (multi-upload success row) ─────────────────────────

function CheckFilledIcon({ fillColor, size = 32 }: { fillColor: string; size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none" aria-hidden>
      <circle cx="16" cy="16" r="15" fill={fillColor} />
      <path d="M9 16L14 21L23 11" stroke="#FFFFFF" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// ─── Filled warning icon (multi-upload error row) ────────────────────────────

function WarningFilledIcon({ fillColor, size = 32 }: { fillColor: string; size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none" aria-hidden>
      <circle cx="16" cy="16" r="15" fill={fillColor} />
      <path d="M16 9V18" stroke="#FFFFFF" strokeWidth="2.5" strokeLinecap="round" />
      <circle cx="16" cy="23" r="1.8" fill="#FFFFFF" />
    </svg>
  )
}

// ─── Multi-upload file row ────────────────────────────────────────────────────

interface MultiUploadFileRowProps {
  file:       UploadFile
  t:          TokenSet
  theme:      DropzoneTheme
  onRemove?:  (id: string) => void
  isLast?:    boolean
}

function MultiUploadFileRow({ file, t, theme, onRemove, isLast }: MultiUploadFileRowProps) {
  const isSuccess   = file.status === 'success'
  const isError     = file.status === 'error' || Boolean(file.error)
  const isUploading = !isSuccess && !isError

  const positiveColor = theme === 'dark' ? s.foreground.positive.default.dark : s.foreground.positive.default.light
  const errorColor    = theme === 'dark' ? s.foreground.negative.default.dark : s.foreground.negative.default.light

  const rowBg =
    isSuccess ? (theme === 'dark' ? translucent.green10                              : s.background.positive.defaultSubtle.light) :
    isError   ? (theme === 'dark' ? s.background.negative.defaultSubtle.dark         : s.background.negative.defaultSubtle.light) :
    t.rowBg

  const docBg        = theme === 'dark' ? s.background.container.dark                : s.background.containerSecondary.light
  const docIconColor = theme === 'dark' ? s.foreground.default.disabled.light        : s.foreground.neutral.mid.light

  return (
    <div
      style={{
        display:         'flex',
        alignItems:      'center',
        gap:             spacing[300],
        padding:         `${spacing[300]} ${spacing[400]}`,
        backgroundColor: rowBg,
        borderBottom:    isLast ? 'none' : `${borderWidth.thin} solid ${t.rowBorder}`,
        transition:      'background-color 150ms ease',
      }}
    >
      {/* Leading icon */}
      <span style={{ flexShrink: 0 }}>
        {isUploading && <DocRoundIcon bgColor={docBg} iconColor={docIconColor} />}
        {isSuccess   && <CheckFilledIcon fillColor={positiveColor} size={32} />}
        {isError     && <WarningFilledIcon fillColor={errorColor} size={32} />}
      </span>

      {/* Content */}
      <span style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: spacing[50] }}>
        <span
          style={{
            fontSize:     typography.fontSize.md,
            fontWeight:   600,
            lineHeight:   '1.43em',
            color:        isError ? errorColor : t.fileNameColor,
            overflow:     'hidden',
            textOverflow: 'ellipsis',
            whiteSpace:   'nowrap',
          }}
        >
          {isSuccess ? 'Upload Completed' : isError ? (file.error ?? 'Upload failed') : file.name}
        </span>
        <span style={{ fontSize: typography.fontSize.sm, lineHeight: '1.667em', color: t.fileSizeColor }}>
          {isError && file.error ? 'Description' : file.size}
        </span>
        {isUploading && file.progress !== undefined && (
          <span style={{ display: 'flex', alignItems: 'center', gap: spacing[200], marginTop: spacing[50] }}>
            <span style={{ flex: 1, height: spacing[100], backgroundColor: t.progressTrack, borderRadius: radius.xs, overflow: 'hidden' }}>
              <span style={{ display: 'block', height: '100%', width: `${file.progress}%`, backgroundColor: t.progressFill, borderRadius: radius.xs, transition: 'width 300ms ease' }} />
            </span>
            <span style={{ fontSize: typography.fontSize.sm, fontWeight: 700, color: positiveColor, flexShrink: 0, minWidth: spacing[800], textAlign: 'right' }}>
              {file.progress}%
            </span>
          </span>
        )}
      </span>

      {/* Action */}
      {onRemove && (
        <Button
          variant="text"
          color="neutral"
          size="sm"
          theme={theme}
          iconOnly
          showLeadingIcon
          aria-label={isUploading ? `Remove ${file.name}` : 'Dismiss'}
          onClick={() => onRemove(file.id)}
          leadingIcon={isUploading ? <DeleteOutline size={16} aria-hidden /> : <CloseOutline size={16} aria-hidden />}
        />
      )}
    </div>
  )
}

// ─── Multi-upload panel ───────────────────────────────────────────────────────

interface MultiUploadPanelProps {
  files:     UploadFile[]
  t:         TokenSet
  theme:     DropzoneTheme
  onRemove?: (id: string) => void
  disabled?: boolean
}

function MultiUploadPanel({ files, t, theme, onRemove, disabled }: MultiUploadPanelProps) {
  const [collapsed, setCollapsed] = useState(false)

  const headerBg     = theme === 'dark' ? s.background.container.dark    : s.background.container.light
  const headerText   = theme === 'dark' ? s.foreground.default.primary.dark  : s.foreground.default.primary.light
  const headerIcon   = theme === 'dark' ? s.foreground.default.disabled.dark : s.foreground.default.disabled.light

  return (
    <div
      style={{
        border:       `${borderWidth.thin} solid ${t.rowBorder}`,
        borderRadius: radius.sm,
        overflow:     'hidden',
        boxShadow:    elevation.level2,
      }}
    >
      {/* Header */}
      <div
        style={{
          display:         'flex',
          alignItems:      'center',
          justifyContent:  'space-between',
          padding:         `${spacing[400]} ${spacing[500]}`,
          backgroundColor: headerBg,
        }}
      >
        <span style={{ fontSize: typography.fontSize.md, fontWeight: 600, lineHeight: '1.5em', color: headerText }}>
          Uploading {files.length} item{files.length !== 1 ? 's' : ''}
        </span>
        <span style={{ display: 'flex', alignItems: 'center', gap: spacing[100] }}>
          {/* Collapse chevron */}
          <Button
            variant="text"
            color="neutral"
            size="sm"
            theme={theme}
            iconOnly
            showLeadingIcon
            aria-label={collapsed ? 'Expand file list' : 'Collapse file list'}
            onClick={() => setCollapsed((x) => !x)}
            leadingIcon={
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden>
                <path
                  d={collapsed ? 'M4 6L8 10L12 6' : 'M4 10L8 6L12 10'}
                  stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"
                />
              </svg>
            }
          />
          {/* Dismiss all */}
          {!disabled && (
            <Button
              variant="text"
              color="neutral"
              size="sm"
              theme={theme}
              iconOnly
              showLeadingIcon
              aria-label="Dismiss all uploads"
              onClick={() => files.forEach((f) => onRemove?.(f.id))}
              leadingIcon={
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden>
                  <path d="M2 2L12 12M12 2L2 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                </svg>
              }
            />
          )}
        </span>
      </div>

      {/* File rows */}
      {!collapsed && (
        <div style={{ backgroundColor: t.rowBg }}>
          {files.map((f, i) => (
            <MultiUploadFileRow
              key={f.id}
              file={f}
              t={t}
              theme={theme}
              onRemove={disabled ? undefined : onRemove}
              isLast={i === files.length - 1}
            />
          ))}
        </div>
      )}
    </div>
  )
}

// ─── File Row ─────────────────────────────────────────────────────────────────

interface FileRowProps {
  file:      UploadFile
  t:         TokenSet
  theme:     DropzoneTheme
  onRemove?: (id: string) => void
  disabled?: boolean
}

function FileRow({ file, t, theme, onRemove, disabled }: FileRowProps) {
  const [hovered, setHovered] = useState(false)

  const isError     = Boolean(file.error) || file.status === 'error'
  const isSuccess   = file.status === 'success'
  const hasProgress = file.progress !== undefined && !isSuccess && !isError

  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        display:         'flex',
        alignItems:      'flex-start',
        gap:             spacing[200],
        padding:         `${spacing[300]} ${spacing[400]}`,
        backgroundColor: hovered && !disabled ? t.rowBgHover : t.rowBg,
        border:          `${borderWidth.thin} solid ${isError ? t.dropBorderError : t.rowBorder}`,
        borderRadius:    radius.sm,
        transition:      'background-color 150ms ease',
        opacity:         disabled ? opacity.half : opacity.full,
      }}
    >
      {/* File type icon */}
      <span style={{ flexShrink: 0, display: 'flex', alignItems: 'center', paddingTop: '2px' }}>
        <FileTypeIcon name={file.name} defaultColor={t.fileIconColor} />
      </span>

      {/* Content: name + meta + progress */}
      <span style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: spacing[50] }}>
        <span
          style={{
            fontSize:     typography.fontSize.md,
            fontWeight:   600,
            lineHeight:   '1.43em',
            color:        isError ? t.dropBorderError : t.fileNameColor,
            overflow:     'hidden',
            textOverflow: 'ellipsis',
            whiteSpace:   'nowrap',
          }}
        >
          {file.name}
        </span>

        {isError && file.error ? (
          <span style={{ fontSize: typography.fontSize.sm, lineHeight: '1.667em', color: t.errorText }}>
            {file.error}
          </span>
        ) : (
          <span style={{ fontSize: typography.fontSize.sm, lineHeight: '1.667em', color: t.fileSizeColor }}>
            {file.size}
          </span>
        )}

        {hasProgress && (
          <span style={{ display: 'flex', alignItems: 'center', gap: spacing[200], marginTop: spacing[50] }}>
            <span
              style={{
                flex:            1,
                height:          spacing[100],
                backgroundColor: t.progressTrack,
                borderRadius:    radius.xs,
                overflow:        'hidden',
              }}
            >
              <span
                style={{
                  display:         'block',
                  height:          '100%',
                  width:           `${file.progress ?? 0}%`,
                  backgroundColor: t.progressFill,
                  borderRadius:    radius.xs,
                  transition:      'width 300ms ease',
                }}
              />
            </span>
            <span
              style={{
                fontSize:   typography.fontSize.sm,
                fontWeight: 600,
                color:      t.progressFill,
                flexShrink: 0,
                minWidth:   spacing[700],
                textAlign:  'right',
              }}
            >
              {file.progress ?? 0}%
            </span>
          </span>
        )}
      </span>

      {/* Status + remove */}
      <span style={{ flexShrink: 0, display: 'flex', alignItems: 'center', gap: spacing[50], paddingTop: scale[25] }}>
        {isSuccess && (
          <Button
            variant="text"
            color="positive"
            size="sm"
            theme={theme}
            iconOnly
            showLeadingIcon
            disabled
            aria-label="Upload successful"
            leadingIcon={<CheckOutline size={16} aria-hidden />}
          />
        )}
        {!disabled && (
          <Button
            variant="text"
            color="neutral"
            size="sm"
            theme={theme}
            iconOnly
            showLeadingIcon
            aria-label={`Remove ${file.name}`}
            onClick={() => onRemove?.(file.id)}
            leadingIcon={<CloseOutline size={16} aria-hidden />}
          />
        )}
      </span>
    </div>
  )
}

// ─── Drop Zone Area ───────────────────────────────────────────────────────────

export type DropzoneUploadState = 'idle' | 'uploading' | 'completed'

interface DropZoneAreaProps {
  inputId:           string
  t:                 TokenSet
  variant:           DropzoneVariant
  accept?:           string
  disabled?:         boolean
  hasError:          boolean
  acceptLabel?:      string
  maxSize?:          number
  onFiles:           (files: File[]) => void
  /** Controls which visual state the drop area renders. Default: 'idle' */
  uploadState?:      DropzoneUploadState
  /** Filename shown inside the drop area during the 'uploading' state */
  uploadingFileName?: string
  /** Called when the × cancel button is clicked during the 'uploading' state */
  onCancelUpload?:   () => void
}

function DropZoneArea({
  inputId, t, variant, accept, disabled, hasError, acceptLabel, maxSize, onFiles,
  uploadState = 'idle', uploadingFileName, onCancelUpload,
}: DropZoneAreaProps) {
  const [isDragOver, setIsDragOver] = useState(false)
  const [isHovered,  setIsHovered]  = useState(false)
  const inputRef                    = useRef<HTMLInputElement>(null)

  const borderColor =
    disabled    ? t.dropBorder :
    hasError    ? t.dropBorderError :
    isDragOver  ? t.dropBorderHover :
    isHovered   ? t.dropBorderHover :
    t.dropBorder

  const bgColor =
    disabled   ? 'transparent' :
    hasError   ? t.dropBgError :
    isDragOver ? t.dropBgHover :
    isHovered  ? t.dropBgHover :
    t.dropBg

  const iconColor =
    disabled   ? t.disabledText :
    isDragOver ? t.dropIconHover :
    isHovered  ? t.dropIconHover :
    t.dropIconDefault

  const handleDragOver = (e: React.DragEvent) => {
    if (disabled) return
    e.preventDefault()
    e.stopPropagation()
    setIsDragOver(true)
  }

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault()
    e.stopPropagation()
    setIsDragOver(false)
  }

  const handleDrop = (e: React.DragEvent) => {
    if (disabled) return
    e.preventDefault()
    e.stopPropagation()
    setIsDragOver(false)
    const dropped = Array.from(e.dataTransfer.files)
    onFiles(variant === 'single' ? dropped.slice(0, 1) : dropped)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = Array.from(e.target.files ?? [])
    onFiles(selected)
    if (inputRef.current) inputRef.current.value = ''
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!disabled && (e.key === 'Enter' || e.key === ' ')) {
      e.preventDefault()
      inputRef.current?.click()
    }
  }

  return (
    <div
      role={uploadState === 'idle' ? 'button' : undefined}
      tabIndex={disabled || uploadState !== 'idle' ? -1 : 0}
      aria-label={variant === 'single' ? 'Drop a file here or click to browse' : 'Drop files here or click to browse'}
      aria-disabled={disabled}
      onClick={() => uploadState === 'idle' && !disabled && inputRef.current?.click()}
      onKeyDown={handleKeyDown}
      onMouseEnter={() => uploadState === 'idle' && !disabled && setIsHovered(true)}
      onMouseLeave={() => { setIsHovered(false); setIsDragOver(false) }}
      onDragOver={uploadState === 'idle' ? handleDragOver : undefined}
      onDragLeave={uploadState === 'idle' ? handleDragLeave : undefined}
      onDrop={uploadState === 'idle' ? handleDrop : undefined}
      className={uploadState === 'idle' ? 'focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px]' : ''}
      style={{
        position:        'relative',
        display:         'flex',
        flexDirection:   'column',
        alignItems:      'center',
        justifyContent:  'center',
        gap:             spacing[300],
        padding:         `${spacing[1000]} ${spacing[600]}`,
        border:          `${borderWidth.default} dashed ${borderColor}`,
        borderRadius:    radius.sm,
        backgroundColor: bgColor,
        cursor:          uploadState !== 'idle' ? 'default' : disabled ? 'not-allowed' : 'pointer',
        outlineColor:    t.focusRing,
        transition:      'background-color 150ms ease, border-color 150ms ease',
        userSelect:      'none',
        textAlign:       'center',
        minHeight:       '160px',
      }}
    >
      {/* ── Uploading state ── */}
      {uploadState === 'uploading' && (
        <>
          <SpinnerIcon trackColor={t.progressTrack} fillColor={t.progressFill} size={48} />
          <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: spacing[100] }}>
            <span style={{ fontSize: typography.fontSize.md, fontWeight: 600, lineHeight: '1.5em', color: t.titleColor }}>
              Uploading file...
            </span>
            {uploadingFileName && (
              <span style={{ fontSize: typography.fontSize.md, fontWeight: 400, lineHeight: '1.43em', color: t.subtitleColor }}>
                {uploadingFileName}
              </span>
            )}
          </span>
          {onCancelUpload && (
            <button
              type="button"
              aria-label="Cancel upload"
              onClick={(e) => { e.stopPropagation(); onCancelUpload() }}
              style={{
                border:     'none',
                background: 'none',
                cursor:     'pointer',
                padding:    spacing[100],
                color:      t.subtitleColor,
                fontSize:   typography.fontSize.lg,
                lineHeight: 1,
                display:    'flex',
                alignItems: 'center',
              }}
            >
              ×
            </button>
          )}
        </>
      )}

      {/* ── Completed state ── */}
      {uploadState === 'completed' && (
        <>
          <UploadCompleteIcon color={t.dropIconHover} size={52} />
          <span style={{ fontSize: typography.fontSize.md, fontWeight: 600, lineHeight: '1.5em', color: t.titleColor }}>
            Upload Completed!
          </span>
        </>
      )}

      {/* ── Idle state ── */}
      {uploadState === 'idle' && (
        <>
          <UploadCloudIcon color={iconColor} size={40} />

          <span style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: spacing[100] }}>
            <span
              style={{
                fontSize:   typography.fontSize.md,
                fontWeight: 600,
                lineHeight: '1.5em',
                color:      disabled ? t.disabledText : t.titleColor,
              }}
            >
              {isDragOver ? 'Drop to upload' : 'Drop files here or click to upload.'}
            </span>

            {(acceptLabel || maxSize) && (
              <span
                style={{
                  fontSize:   typography.fontSize.sm,
                  fontWeight: 400,
                  lineHeight: '1.43em',
                  color:      disabled ? t.disabledText : t.subtitleColor,
                  marginTop:  spacing[50],
                }}
              >
                {[
                  acceptLabel && `Supports: ${acceptLabel}`,
                  maxSize    && `Max. file size: ${formatBytes(maxSize)}`,
                ].filter(Boolean).join(' · ')}
              </span>
            )}

            {!acceptLabel && !maxSize && (
              <span
                style={{
                  fontSize:   typography.fontSize.md,
                  fontWeight: 400,
                  lineHeight: '1.43em',
                  color:      disabled ? t.disabledText : t.subtitleColor,
                }}
              >
                or{' '}
                <span
                  style={{
                    color:               disabled ? t.disabledText : t.browseColor,
                    fontWeight:          600,
                    textDecoration:      'underline',
                    textDecorationColor: disabled ? t.disabledText : t.browseColor,
                    textUnderlineOffset: '2px',
                  }}
                >
                  browse files
                </span>
              </span>
            )}
          </span>
        </>
      )}

      {/* Hidden native file input */}
      <input
        ref={inputRef}
        id={inputId}
        type="file"
        accept={accept}
        multiple={variant === 'multiple'}
        disabled={disabled}
        onChange={handleInputChange}
        aria-hidden
        tabIndex={-1}
        style={{
          position: 'absolute',
          width:    0,
          height:   0,
          opacity:  0,
          overflow: 'hidden',
        }}
      />
    </div>
  )
}

// ─── DropzoneAndUpload ────────────────────────────────────────────────────────

function DropzoneAndUpload({
  variant       = 'single',
  theme         = 'light',
  files:         controlledFiles,
  defaultFiles  = [],
  onChange,
  onRemove,
  accept,
  maxSize,
  acceptLabel,
  label,
  helperText:   helperTextProp,
  error,
  disabled      = false,
  required      = false,
  uploadState,
  uploadingFileName,
  onCancelUpload,
  className,
  style,
}: DropzoneAndUploadProps) {
  const inputId      = useId()
  const t            = tokens[theme]
  const isControlled = controlledFiles !== undefined

  const [internalFiles, setInternalFiles] = useState<UploadFile[]>(defaultFiles)
  const [sizeError, setSizeError]         = useState<string | null>(null)
  const files = isControlled ? controlledFiles! : internalFiles

  // Clear stale size rejection error when the maxSize limit changes (FU5)
  useEffect(() => { setSizeError(null) }, [maxSize])

  const setFiles = useCallback((next: UploadFile[]) => {
    if (!isControlled) setInternalFiles(next)
    onChange?.(next)
  }, [isControlled, onChange])

  const handleFiles = useCallback((incoming: File[]) => {
    if (maxSize) {
      const rejected = incoming.filter((f) => f.size > maxSize)
      if (rejected.length > 0) {
        const limit = formatBytes(maxSize)
        setSizeError(
          rejected.length === 1
            ? `"${rejected[0].name}" exceeds the ${limit} file size limit.`
            : `${rejected.length} files exceed the ${limit} file size limit.`
        )
      } else {
        setSizeError(null)
      }
    }

    const eligible = maxSize ? incoming.filter((f) => f.size <= maxSize) : incoming
    const newFiles  = eligible.map(makeUploadFile)

    let next: UploadFile[]
    if (variant === 'single') {
      next = newFiles.slice(0, 1)
    } else {
      // De-duplicate by name
      const existingNames = new Set(files.map((f) => f.name))
      const unique = newFiles.filter((f) => !existingNames.has(f.name))
      next = [...files, ...unique]
    }

    setFiles(next)
  }, [files, variant, maxSize, setFiles])

  const handleRemove = useCallback((id: string) => {
    const next = files.filter((f) => f.id !== id)
    onRemove?.(id)
    setFiles(next)
  }, [files, onRemove, setFiles])

  const handleClearAndReplace = useCallback(() => {
    setFiles([])
  }, [setFiles])

  const hasFiles         = files.length > 0
  const showDropZone     = variant === 'multiple' || !hasFiles
  const showSingleFiles  = variant === 'single'   && hasFiles
  const showMultiFiles   = variant === 'multiple'  && hasFiles
  const activeError      = error ?? sizeError ?? null

  return (
    <div
      className={cn(className)}
      style={{
        display:       'flex',
        flexDirection: 'column',
        gap:           spacing[100],
        ...style,
      }}
    >
      {/* Label */}
      {label && (
        <label
          htmlFor={inputId}
          style={{
            display:    'block',
            fontSize:   typography.fontSize.md,
            fontWeight: 600,
            lineHeight: '1.43em',
            color:      disabled ? t.disabledText : t.labelColor,
            cursor:     disabled ? 'not-allowed' : 'default',
            userSelect: 'none',
          }}
        >
          {label}
          {required && (
            <span style={{ color: t.dropBorderError, marginLeft: spacing[50] }} aria-hidden>
              *
            </span>
          )}
        </label>
      )}

      {/* Drop zone */}
      {showDropZone && (
        <DropZoneArea
          inputId={inputId}
          t={t}
          variant={variant}
          accept={accept}
          disabled={disabled}
          hasError={Boolean(activeError)}
          acceptLabel={acceptLabel}
          maxSize={maxSize}
          onFiles={handleFiles}
          uploadState={uploadState}
          uploadingFileName={uploadingFileName}
          onCancelUpload={onCancelUpload}
        />
      )}

      {/* Single variant — file row replaces the drop zone */}
      {showSingleFiles && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: spacing[200] }}>
          {files.map((f) => (
            <FileRow key={f.id} file={f} t={t} theme={theme} onRemove={handleRemove} disabled={disabled} />
          ))}

          {!disabled && (
            <Button
              variant="outline"
              color="positive"
              size="sm"
              theme={theme}
              onClick={handleClearAndReplace}
            >
              Replace file
            </Button>
          )}
        </div>
      )}

      {/* Multiple variant — upload panel */}
      {showMultiFiles && (
        <MultiUploadPanel
          files={files}
          t={t}
          theme={theme}
          onRemove={handleRemove}
          disabled={disabled}
        />
      )}

      {/* Helper / Error text */}
      {(activeError || helperTextProp) && (
        <span
          role={activeError ? 'alert' : undefined}
          style={{
            fontSize:   typography.fontSize.sm,
            fontWeight: 400,
            lineHeight: '1.667em',
            color:      activeError ? t.errorText : t.helperTextColor,
            marginTop:  spacing[50],
          }}
        >
          {activeError ?? helperTextProp}
        </span>
      )}
    </div>
  )
}

DropzoneAndUpload.displayName = 'DropzoneAndUpload'

export { DropzoneAndUpload }
export default DropzoneAndUpload
